
data_name: shades2
data_arguments:
    number_of_samples: 30
    grid_size: 224 
    side_length: 8
    shade_contrast: 0.15
    separate: 0
    corners: [1,2,4]
    save: False
    images: "/mn/kadingir/vegardantun_000000/nobackup/NN_security_data/data/shades_vis_images
"
    labels: ""
    difference: ""
    model: 3
    model_dest: model

#data_name: contrast 
#data_arguments:
#    number_of_samples: 300
#    grid_size: 224
#    shift: False 
#    epsilon: 1
#    save: False 
#    images: "data_trainn_images"
#    labels: "data_trainn_labels"
#    difference: "data_trainn_diff"
#data_arguments:
#    grid_size: 32
#    line_width:  3
#    a: 0.01
#    flip_a_values: False 
#    data_size: 1000
#    low_a_value: 0.009
#
#data_name: stripe_train
#data_arguments:
#    grid_size: 32
#    line_width:  3
#    a: 0.01
#    flip_a_values: False
#
#data_name: lines_train
#data_arguments:
#    number_of_samples: 100
#    grid_size: 128 
#    side_length: 80
#    width: 4
#    shift: True
#    epsilon: 1
#    save: False 
#    images: "data_trainn_images"
#    labels: "data_trainn_labels"

