

DATASET_TRAIN:
    name: stripe_train
    arguments:
        grid_size: 32
        line_width:  3
        a: 0.01
        flip_a_values: False

DATASET_VAL:
    name: stripe_test
    arguments:
        grid_size: 32
        line_width:  3
        a: 0.01
        flip_a_values: False 
        data_size: 1000
        low_a_value: 0.009

DATASET_TEST:
    name: stripe_test
    arguments:
        grid_size: 32
        line_width:  3
        a: 0.01
        flip_a_values: True 
        data_size: 1000
        low_a_value: 0.000

MODEL:
    name: cnn3
    arguments:    
        act: relu
        final_act: sigmoid
        bias_initializer: zeros

MODEL_METADATA:
    precision: float64
    save_final_model: yes
    dest_model: model
    model_number_type: fixed
    model_number_arguments:
        model_id: 2
        counter_path: ./
    save_best_model:
        use_model_checkpoint: yes
        arguments:
            filepath: best_model_demo.h5
            monitor: val_acc
            verbose: 1
            save_best_only: False
            mode: max
            period: 1

TRAIN:
    batch_size: 500
    shuffle: no
    validate_every: 50
    optim:
        type: adam
        arguments:
            param1: none
    max_epoch: 500 
    stopping_criteria:
        type: epoch
        arguments:
            monitor: val_acc
            mode: auto
            verbose: 1
            patience: 5

    loss:
        type: binary_crossentropy
        arguments:
            param1: none
    metrics:
        metric1: accuracy

COMPUTER_SETUP:
    use_gpu: yes
    compute_node: 0

INFORMATION_TRAIN:
    save_every: 10
    print_every: 10
    plot:
        font_size: 15
        loss_train: no
        accuracy_train: no


