ATTACK:
    name: 'L2DeepFoolAttack'
    arguments:
        epsilon: 'custom'

DATASET:
    name: 'existing'
    arguments:
        number_of_samples: 1
        grid_size: 224
        side_length: 8
        shade_contrast: 0
        separate: 0
        corners: [1, 2, 4]
        save: True 
        images: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_imagesnoiseless" 
        labels: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_labels" 
        difference: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_difference" 
        original_images: "data/original_images_cnndrop_L2DF2"
        adv_images: "/itf-fi-ml/home/znliu/data/shades_data/adv_attacks_images_cnndrop_any_fix"
        adv_labels: "/itf-fi-ml/home/znliu/data/shades_data/adv_attacks_labels_cnndrop_any_fix"
        adv_diffs: "/itf-fi-ml/home/znliu/data/shades_data/adv_attacks_diff_cnndrop_any_fix"
        model: 1
    train_arguments:
        number_of_samples: 1
        grid_size: 224
        side_length: 8
        shade_contrast: 0
        separate: 0
        corners: [1, 2, 4]
        save: True 
        images: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_images"
        labels: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_labels" 
        difference: "/itf-fi-ml/home/znliu/data/shades_data/fixed_shades_train_nosep_difference" 
        model: 1

MODEL:
    name: cnndrop
    arguments:    
        act: relu
        final_act: sigmoid
        bias_initializer: zeros

MODEL_METADATA:
    precision: float64
    save_final_model: yes
    dest_model: model
    model_number_type: fixed
    model_number_arguments:
        model_id: 800
        counter_path: ./
    save_best_model:
        use_model_checkpoint: yes
        arguments:
            filepath: best_model_cnndrop.h5
            monitor: val_acc
            verbose: 1
            save_best_only: False
            mode: max
            period: 1

TRAIN:
    batch_size: 500
    shuffle: no
    validate_every: 1000
    optim:
        type: adam
        arguments:
            param1: none
    max_epoch: 50 
    stopping_criteria:
        type: epoch
        arguments:
            monitor: val_acc
            mode: auto
            verbose: 1
            patience: 5

    loss:
        type: SparseCategoricalCrossentropy
        arguments:
            param1: none
    metrics:
        metric1: accuracy

COMPUTER_SETUP:
    use_gpu: yes
    compute_node: 1

INFORMATION_TRAIN:
    save_every: 10
    print_every: 10
    plot:
        font_size: 15
        loss_train: no
        accuracy_train: no


